-- LEGENDS · сид: перенос текущих данных из data.js. Одноразовый.

-- Вершины
insert into peaks (name, alt) values ('Такао', 599) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Дзимба', 855) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Митакэ', 929) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Одакэ', 1266) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Сэнгэн', 802) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Таканосу', 834) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Танзава', 1491) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Кинпу-сан', 2599) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Кинтоки', 1212) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Кумотори', 2017) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Дзидзо-дакэ', 2764) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Каннон-дакэ', 2841) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Якуси-дакэ', 2780) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Яригатакэ', 3180) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Яцугатакэ', 2500) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Боноорэ', 969) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Мизугаки', 2230) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Акадакэ', 2899) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Пунта дель Ранчи', null) on conflict (name) do update set alt = excluded.alt;
insert into peaks (name, alt) values ('Пунта Кватро Сорелле', 2600) on conflict (name) do update set alt = excluded.alt;

-- Нишевые
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('kianu', 'Киану', null, null, 'active', 'creator', '{"Организатор","Путеводитель","Навигатор","Разведчик"}', 'Токио', 'Осталось ещё 20 минут.', 355) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('mark', 'Марк', 'Акула-молоток', null, 'active', 'deity', '{"Лекарь","Саппорт","Оруженосец","Водитель"}', 'Токио', null, 205) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('nastya', 'Анастасия', 'МВД', 'Токсичность', 'active', 'deity', '{"Разведчик","Плюс вайб"}', 'Токио', null, 320) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('sonya-birka', 'Соня', 'Бирка', 'Скалолаз', 'gone', 'legend', '{"Фото/видео","Мыльница","Скромняжка","Новое поколение"}', 'Китай', null, 30) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('sonya-druid', 'Соня', 'Друид', null, 'gone', 'legend', '{"Плюс вайб"}', 'Китай', null, 140) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('mira', 'Мира', 'Торг', null, 'gone', 'legend', '{"Плюс вайб","Разведчик","Алкоголик","Новое поколение"}', 'Россия', null, 45) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('prohor', 'Прохор', 'Колонка', null, 'active', 'legend', '{"Плюс вайб","Разведчик","Новое поколение"}', 'Токио', null, 15) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('maksim', 'Максим', 'AI', null, 'gone', 'legend', '{"Водитель","Интеллект","Скромняжка"}', 'Россия', null, 55) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('miroslav', 'Мирослав', '2010', null, 'gone', 'legend', '{"Фото/видео","Плюс вайб","Новое поколение","Разведчик","Наркоман"}', 'Россия', null, 35) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('marina', 'Марина', 'Спортик', null, 'gone', 'legend', '{"Фото/видео","Плюс вайб","Скромняжка"}', 'Россия', null, 50) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('aleksandr', 'Александр', 'Клёш', null, 'active', 'legend', '{"Фото/видео","Плюс вайб"}', 'Токио', null, 28) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('andrey', 'Андрей', 'Стафовый кодер', null, 'gone', 'legend', '{"Наркоман","Разведчик"}', 'Лондон', null, 42) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('viktor', 'Виктор', null, null, 'gone', 'legend', '{}', 'неизвестно', null, 48) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('zhenya', 'Женя', 'Валькирия', null, 'gone', 'mythic', '{"Новое поколение"}', 'Россия', null, 280) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('yura', 'Юра', 'Нет пути домой', null, 'active', 'mythic', '{"Водитель","Скромняжка"}', 'Токио', null, 250) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('tima-instruktor', 'Тима', 'Инструктор', null, 'active', 'mythic', '{"Водитель","Скромняжка"}', 'Токио', null, 300) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('ksyusha', 'Ксюша', 'Ящер', null, 'active', 'mythic', '{"Скромняжка"}', 'Токио', null, 95) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('albina', 'Альбина', null, 'Художник', 'active', 'mythic', '{"Товарищ","Плюс вайб","Фото/видео","Новое поколение"}', 'Токио', null, 335) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('ulyana', 'Ульяна', 'Медуза Горгона', null, 'active', 'mythic', '{"Скромняжка"}', 'Токио', null, 175) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('vika-raskladushka', 'Вика', 'Раскладушка', null, 'active', 'mythic', '{"Фото/видео"}', 'Токио', null, 265) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('tima-sledopyt', 'Тима', 'Следопыт', null, 'gone', 'mythic', '{"Алкоголик","Наркоман","Новое поколение"}', 'Латвия', null, 290) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('arkadiy', 'Аркадий', 'Тибетский монах', null, 'gone', 'mythic', '{"Разведчик"}', 'Китай', null, 310) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('anya-poteryashka', 'Аня', 'Потеряшка', null, 'active', 'knight', '{}', 'Токио', null, 215) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('eson', 'Эсон', 'Турбонаддув', null, 'active', 'knight', '{}', 'Токио', null, 200) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('tadahiro', 'Тадахиро', 'Элайджо', null, 'active', 'knight', '{"Фото/видео"}', 'Токио', null, 190) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('anya-glina', 'Аня', 'Глиномес', null, 'gone', 'pathfinder', '{}', 'неизвестно', null, 25) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('vanya', 'Ваня', 'Енот', null, 'active', 'pathfinder', '{}', 'Токио', null, 155) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('ira', 'Ира', 'Мать Кабанов', null, 'gone', 'pathfinder', '{}', 'Китай', null, 130) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('kseniya', 'Ксения', null, null, 'gone', 'pathfinder', '{}', 'неизвестно', null, 145) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('anya-2', 'Аня', null, null, 'active', 'recruit', '{"Новое поколение"}', 'Токио', null, 210) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('yulya', 'Юля', null, null, 'active', 'recruit', '{"Новое поколение"}', 'Токио', null, 195) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('masha', 'Маша', null, null, 'active', 'recruit', '{}', 'Токио', null, 230) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('matvey', 'Матвей', 'Распутник', null, 'active', 'recruit', '{"Наркоман","Новое поколение"}', 'Токио', null, 10) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('irina', 'Ирина', null, null, 'active', 'recruit', '{}', 'Токио', null, 220) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('natalya', 'Наталья', null, null, 'gone', 'recruit', '{}', 'неизвестно', null, 205) on conflict (id) do nothing;
insert into members (id, name, nick, title, status, rank, roles, place, quote, hue) values ('vika', 'Вика', null, null, 'active', 'recruit', '{}', 'Токио', null, 260) on conflict (id) do nothing;

-- Летопись
insert into hikes (name, seq) select 'Дзимба → Такао', 1 where not exists (select 1 from hikes where seq = 1);
insert into hike_peaks (hike_id, peak) select h.id, 'Дзимба' from hikes h where h.seq = 1 on conflict do nothing;
insert into hike_peaks (hike_id, peak) select h.id, 'Такао' from hikes h where h.seq = 1 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 1 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 1 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ira' from hikes h where h.seq = 1 on conflict do nothing;
insert into hikes (name, seq) select 'Митакэ — Одакэ', 2 where not exists (select 1 from hikes where seq = 2);
insert into hike_peaks (hike_id, peak) select h.id, 'Митакэ' from hikes h where h.seq = 2 on conflict do nothing;
insert into hike_peaks (hike_id, peak) select h.id, 'Одакэ' from hikes h where h.seq = 2 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 2 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'viktor' from hikes h where h.seq = 2 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'sonya-birka' from hikes h where h.seq = 2 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 2 on conflict do nothing;
insert into hikes (name, seq) select 'Хаконэ: Сэнгэн → Таканосу', 3 where not exists (select 1 from hikes where seq = 3);
insert into hike_peaks (hike_id, peak) select h.id, 'Сэнгэн' from hikes h where h.seq = 3 on conflict do nothing;
insert into hike_peaks (hike_id, peak) select h.id, 'Таканосу' from hikes h where h.seq = 3 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 3 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 3 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'viktor' from hikes h where h.seq = 3 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'sonya-birka' from hikes h where h.seq = 3 on conflict do nothing;
insert into hikes (name, seq) select 'Танзава', 4 where not exists (select 1 from hikes where seq = 4);
insert into hike_peaks (hike_id, peak) select h.id, 'Танзава' from hikes h where h.seq = 4 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 4 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'viktor' from hikes h where h.seq = 4 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 4 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'sonya-birka' from hikes h where h.seq = 4 on conflict do nothing;
insert into hikes (name, seq) select 'Дзимба → Такао', 5 where not exists (select 1 from hikes where seq = 5);
insert into hike_peaks (hike_id, peak) select h.id, 'Дзимба' from hikes h where h.seq = 5 on conflict do nothing;
insert into hike_peaks (hike_id, peak) select h.id, 'Такао' from hikes h where h.seq = 5 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'sonya-druid' from hikes h where h.seq = 5 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'sonya-birka' from hikes h where h.seq = 5 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ira' from hikes h where h.seq = 5 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 5 on conflict do nothing;
insert into hikes (name, seq) select 'Кинпу-сан', 6 where not exists (select 1 from hikes where seq = 6);
insert into hike_peaks (hike_id, peak) select h.id, 'Кинпу-сан' from hikes h where h.seq = 6 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 6 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 6 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'sonya-druid' from hikes h where h.seq = 6 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'andrey' from hikes h where h.seq = 6 on conflict do nothing;
insert into hikes (name, seq) select 'Кинтоки-яма', 7 where not exists (select 1 from hikes where seq = 7);
insert into hike_peaks (hike_id, peak) select h.id, 'Кинтоки' from hikes h where h.seq = 7 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 7 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kseniya' from hikes h where h.seq = 7 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'arkadiy' from hikes h where h.seq = 7 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 7 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'andrey' from hikes h where h.seq = 7 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'miroslav' from hikes h where h.seq = 7 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 7 on conflict do nothing;
insert into hikes (name, seq) select 'Кумотори', 8 where not exists (select 1 from hikes where seq = 8);
insert into hike_peaks (hike_id, peak) select h.id, 'Кумотори' from hikes h where h.seq = 8 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 8 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 8 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'andrey' from hikes h where h.seq = 8 on conflict do nothing;
insert into hikes (name, seq) select 'Хоо-дзан «Феникс»', 9 where not exists (select 1 from hikes where seq = 9);
insert into hike_peaks (hike_id, peak) select h.id, 'Дзидзо-дакэ' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_peaks (hike_id, peak) select h.id, 'Каннон-дакэ' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_peaks (hike_id, peak) select h.id, 'Якуси-дакэ' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ira' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'tadahiro' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'tima-instruktor' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 9 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 9 on conflict do nothing;
insert into hikes (name, seq) select 'Камикочи → Яригатакэ', 10 where not exists (select 1 from hikes where seq = 10);
insert into hike_peaks (hike_id, peak) select h.id, 'Яригатакэ' from hikes h where h.seq = 10 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'andrey' from hikes h where h.seq = 10 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 10 on conflict do nothing;
insert into hikes (name, seq) select 'Яцугатакэ', 11 where not exists (select 1 from hikes where seq = 11);
insert into hike_peaks (hike_id, peak) select h.id, 'Яцугатакэ' from hikes h where h.seq = 11 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 11 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 11 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'marina' from hikes h where h.seq = 11 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'anya-glina' from hikes h where h.seq = 11 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'natalya' from hikes h where h.seq = 11 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 11 on conflict do nothing;
insert into hikes (name, seq) select 'Боноорэ', 12 where not exists (select 1 from hikes where seq = 12);
insert into hike_peaks (hike_id, peak) select h.id, 'Боноорэ' from hikes h where h.seq = 12 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'natalya' from hikes h where h.seq = 12 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'anya-glina' from hikes h where h.seq = 12 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'maksim' from hikes h where h.seq = 12 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'arkadiy' from hikes h where h.seq = 12 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'aleksandr' from hikes h where h.seq = 12 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 12 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 12 on conflict do nothing;
insert into hikes (name, seq) select 'Мизугаки', 13 where not exists (select 1 from hikes where seq = 13);
insert into hike_peaks (hike_id, peak) select h.id, 'Мизугаки' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mira' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'marina' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'prohor' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'tima-instruktor' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'tima-sledopyt' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'arkadiy' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'maksim' from hikes h where h.seq = 13 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 13 on conflict do nothing;
insert into hikes (name, seq) select 'Акадакэ', 14 where not exists (select 1 from hikes where seq = 14);
insert into hike_peaks (hike_id, peak) select h.id, 'Акадакэ' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'albina' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'tima-sledopyt' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'prohor' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'anya-poteryashka' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'marina' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ulyana' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'vika-raskladushka' from hikes h where h.seq = 14 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 14 on conflict do nothing;
insert into hikes (name, seq) select 'Митакэ — Одакэ', 15 where not exists (select 1 from hikes where seq = 15);
insert into hike_peaks (hike_id, peak) select h.id, 'Митакэ' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_peaks (hike_id, peak) select h.id, 'Одакэ' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'miroslav' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'andrey' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'matvey' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ira' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'albina' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ulyana' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'marina' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'aleksandr' from hikes h where h.seq = 15 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ksyusha' from hikes h where h.seq = 15 on conflict do nothing;
insert into hikes (name, seq) select 'Юцуги', 16 where not exists (select 1 from hikes where seq = 16);
insert into hike_members (hike_id, member_id) select h.id, 'aleksandr' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'prohor' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'masha' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'anya-poteryashka' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ksyusha' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'ulyana' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'vika-raskladushka' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'yura' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'nastya' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'mark' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'albina' from hikes h where h.seq = 16 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 16 on conflict do nothing;
insert into hikes (name, seq) select 'Пунта дель Ранчи (Италия)', 17 where not exists (select 1 from hikes where seq = 17);
insert into hike_peaks (hike_id, peak) select h.id, 'Пунта дель Ранчи' from hikes h where h.seq = 17 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 17 on conflict do nothing;
insert into hikes (name, seq) select 'Пунта Кватро Сорелле (Италия)', 18 where not exists (select 1 from hikes where seq = 18);
insert into hike_peaks (hike_id, peak) select h.id, 'Пунта Кватро Сорелле' from hikes h where h.seq = 18 on conflict do nothing;
insert into hike_members (hike_id, member_id) select h.id, 'kianu' from hikes h where h.seq = 18 on conflict do nothing;
