// Реальный состав «нишевых». Ранги (по возрастанию): Новобранец (серый, без свечения)
// → Путник (зелёный, аура листвы) → Рыцарь (синий) → Мифик (фиолетовый)
// → Легенда (оранжевый) → Божество (радуга) → Создатель (красная полоса, только Киану).
// peaks: [{ n: гора, t: сколько раз }] — пока пусто, заполнится позже.
// photo: 'photos/имя.jpg' — положи файл в папку photos/ и укажи путь, фото заменит инициалы.

const RANKS = {
  creator:    { label: 'Создатель',  plural: 'Создатель',  c: '#ff4655' },
  deity:      { label: 'Божество',   plural: 'Божества',   c: '#ffb74d' },
  legend:     { label: 'Легенда',    plural: 'Легенды',    c: '#f59a2c' },
  mythic:     { label: 'Мифик',      plural: 'Мифики',     c: '#c07ef7' },
  knight:     { label: 'Рыцарь',     plural: 'Рыцари',     c: '#5fa8f5' },
  pathfinder: { label: 'Путник',     plural: 'Путники',    c: '#4ade80' },
  recruit:    { label: 'Новобранец', plural: 'Новобранцы', c: '#97a1b2' },
};

const RANK_ORDER = ['creator', 'deity', 'legend', 'mythic', 'knight', 'pathfinder', 'recruit'];

const HEROES = [
  // ── Создатель ────────────────────────────────────────────
  { id: 'kianu', name: 'Киану', nick: null, status: 'active', rank: 'creator',
    roles: ['Организатор', 'Путеводитель', 'Навигатор', 'Разведчик'],
    peaks: [], place: 'Токио', quote: 'Осталось ещё 20 минут.', photo: null, hue: 355 },

  // ── Божества ─────────────────────────────────────────────
  { id: 'mark', name: 'Марк', nick: 'Акула-молоток', status: 'active', rank: 'deity',
    roles: ['Лекарь', 'Саппорт', 'Оруженосец', 'Водитель'],
    peaks: [], place: 'Токио', photo: null, hue: 205 },
  { id: 'nastya', name: 'Анастасия', nick: 'МВД', status: 'active', rank: 'deity',
    title: 'Токсичность',
    roles: ['Разведчик', 'Плюс вайб'],
    peaks: [], place: 'Токио', photo: null, hue: 320 },

  // ── Легенды ──────────────────────────────────────────────
  { id: 'sonya-birka', name: 'Соня', nick: 'Бирка', status: 'gone', rank: 'legend',
    title: 'Скалолаз',
    roles: ['Фото/видео', 'Мыльница', 'Скромняжка', 'Новое поколение'],
    peaks: [], place: 'Китай', photo: null, hue: 30 },
  { id: 'sonya-druid', name: 'Соня', nick: 'Друид', status: 'gone', rank: 'legend',
    roles: ['Плюс вайб'],
    peaks: [], place: 'Китай', photo: null, hue: 140 },
  { id: 'mira', name: 'Мира', nick: 'Торг', status: 'gone', rank: 'legend',
    roles: ['Плюс вайб', 'Разведчик', 'Алкоголик', 'Новое поколение'],
    peaks: [], place: 'Россия', photo: null, hue: 45 },
  { id: 'prohor', name: 'Прохор', nick: 'Колонка', status: 'active', rank: 'legend',
    roles: ['Плюс вайб', 'Разведчик', 'Новое поколение'],
    peaks: [], place: 'Токио', photo: null, hue: 15 },
  { id: 'maksim', name: 'Максим', nick: 'AI', status: 'gone', rank: 'legend',
    roles: ['Водитель', 'Интеллект', 'Скромняжка'],
    peaks: [], place: 'Россия', photo: null, hue: 55 },
  { id: 'miroslav', name: 'Мирослав', nick: '2010', status: 'gone', rank: 'legend',
    roles: ['Фото/видео', 'Плюс вайб', 'Новое поколение', 'Разведчик', 'Наркоман'],
    peaks: [], place: 'Россия', photo: null, hue: 35 },
  { id: 'marina', name: 'Марина', nick: 'Спортик', status: 'gone', rank: 'legend',
    roles: ['Фото/видео', 'Плюс вайб', 'Скромняжка'],
    peaks: [], place: 'Россия', photo: null, hue: 50 },
  { id: 'aleksandr', name: 'Александр', nick: 'Клёш', status: 'active', rank: 'legend',
    roles: ['Фото/видео', 'Плюс вайб'],
    peaks: [], place: 'Токио', photo: null, hue: 28 },
  { id: 'andrey', name: 'Андрей', nick: 'Стафовый кодер', status: 'gone', rank: 'legend',
    roles: ['Наркоман', 'Разведчик'],
    peaks: [], place: 'Лондон', photo: null, hue: 42 },
  { id: 'viktor', name: 'Виктор', nick: null, status: 'gone', rank: 'legend',
    roles: [],
    peaks: [], place: 'неизвестно', photo: null, hue: 48 },

  // ── Мифики ───────────────────────────────────────────────
  { id: 'zhenya', name: 'Женя', nick: 'Валькирия', status: 'gone', rank: 'mythic',
    roles: ['Новое поколение'],
    peaks: [], place: 'Россия', photo: null, hue: 280 },
  { id: 'yura', name: 'Юра', nick: 'Нет пути домой', status: 'active', rank: 'mythic',
    roles: ['Водитель', 'Скромняжка'],
    peaks: [], place: 'Токио', photo: null, hue: 250 },
  { id: 'tima-instruktor', name: 'Тима', nick: 'Инструктор', status: 'active', rank: 'mythic',
    roles: ['Водитель', 'Скромняжка'],
    peaks: [], place: 'Токио', photo: null, hue: 300 },
  { id: 'ksyusha', name: 'Ксюша', nick: 'Ящер', status: 'active', rank: 'mythic',
    roles: ['Скромняжка'],
    peaks: [], place: 'Токио', photo: null, hue: 95 },
  { id: 'albina', name: 'Альбина', nick: null, status: 'active', rank: 'mythic',
    title: 'Художник',
    roles: ['Товарищ', 'Плюс вайб', 'Фото/видео', 'Новое поколение'],
    peaks: [], place: 'Токио', photo: null, hue: 335 },
  { id: 'ulyana', name: 'Ульяна', nick: 'Медуза Горгона', status: 'active', rank: 'mythic',
    roles: ['Скромняжка'],
    peaks: [], place: 'Токио', photo: null, hue: 175 },
  { id: 'vika-raskladushka', name: 'Вика', nick: 'Раскладушка', status: 'active', rank: 'mythic',
    roles: ['Фото/видео'],
    peaks: [], place: 'Токио', photo: null, hue: 265 },
  { id: 'tima-sledopyt', name: 'Тима', nick: 'Следопыт', status: 'gone', rank: 'mythic',
    roles: ['Алкоголик', 'Наркоман', 'Новое поколение'],
    peaks: [], place: 'Латвия', photo: null, hue: 290 },
  { id: 'arkadiy', name: 'Аркадий', nick: 'Тибетский монах', status: 'gone', rank: 'mythic',
    roles: ['Разведчик'],
    peaks: [], place: 'Китай', photo: null, hue: 310 },

  // ── Рыцари ───────────────────────────────────────────────
  { id: 'anya-poteryashka', name: 'Аня', nick: 'Потеряшка', status: 'active', rank: 'knight',
    roles: [],
    peaks: [], place: 'Токио', photo: null, hue: 215 },
  { id: 'eson', name: 'Эсон', nick: 'Турбонаддув', status: 'active', rank: 'knight',
    roles: [],
    peaks: [], place: 'Токио', photo: null, hue: 200 },
  { id: 'tadahiro', name: 'Тадахиро', nick: 'Элайджо', status: 'active', rank: 'knight',
    roles: ['Фото/видео'],
    peaks: [], place: 'Токио', photo: null, hue: 190 },

  // ── Путники ──────────────────────────────────────────────
  { id: 'anya-glina', name: 'Аня', nick: 'Глиномес', status: 'gone', rank: 'pathfinder',
    roles: [],
    peaks: [], place: 'неизвестно', photo: null, hue: 25 },
  { id: 'vanya', name: 'Ваня', nick: 'Енот', status: 'active', rank: 'pathfinder',
    roles: [],
    peaks: [], place: 'Токио', photo: null, hue: 155 },
  { id: 'ira', name: 'Ира', nick: 'Мать Кабанов', status: 'gone', rank: 'pathfinder',
    roles: [],
    peaks: [], place: 'Китай', photo: null, hue: 130 },
  { id: 'kseniya', name: 'Ксения', nick: null, status: 'gone', rank: 'pathfinder',
    roles: [],
    peaks: [], place: 'неизвестно', photo: null, hue: 145 },

  // ── Новобранцы ───────────────────────────────────────────
  { id: 'anya-2', name: 'Аня', nick: null, status: 'active', rank: 'recruit',
    roles: ['Новое поколение'],
    peaks: [], place: 'Токио', photo: null, hue: 210 },
  { id: 'yulya', name: 'Юля', nick: null, status: 'active', rank: 'recruit',
    roles: ['Новое поколение'],
    peaks: [], place: 'Токио', photo: null, hue: 195 },
  { id: 'masha', name: 'Маша', nick: null, status: 'active', rank: 'recruit',
    roles: [],
    peaks: [], place: 'Токио', photo: null, hue: 230 },
  { id: 'matvey', name: 'Матвей', nick: 'Распутник', status: 'active', rank: 'recruit',
    roles: ['Наркоман', 'Новое поколение'],
    peaks: [], place: 'Токио', photo: null, hue: 10 },
  { id: 'irina', name: 'Ирина', nick: null, status: 'active', rank: 'recruit',
    roles: [],
    peaks: [], place: 'Токио', photo: null, hue: 220 },
  { id: 'natalya', name: 'Наталья', nick: null, status: 'gone', rank: 'recruit',
    roles: [],
    peaks: [], place: 'неизвестно', photo: null, hue: 205 },
  { id: 'vika', name: 'Вика', nick: null, status: 'active', rank: 'recruit',
    roles: [],
    peaks: [], place: 'Токио', photo: null, hue: 260 },
];
