// Реальный состав «нишевых». Ранги (по возрастанию): Новобранец (серый, без свечения)
// → Путник (зелёный, аура листвы) → Рыцарь (синий) → Мифик (фиолетовый)
// → Легенда (оранжевый) → Божество (радуга) → Создатель (красная полоса, только Киану).
// photo: 'photos/имя.jpg' — положи файл в папку photos/ и укажи путь, фото заменит инициалы.
// Хайки — события в HIKES внизу файла: у каждого имя, вершины и состав (crew = id героев).
// Счётчики хайков и вершин у героев считаются из HIKES автоматически.

const RANKS = {
  creator:    { label: 'Создатель',  plural: 'Создатель',  c: '#ff4655' },
  deity:      { label: 'Божество',   plural: 'Божества',   c: '#ffb74d' },
  legend:     { label: 'Легенда',    plural: 'Легенды',    c: '#f59a2c' },
  mythic:     { label: 'Мифик',      plural: 'Мифики',     c: '#c07ef7' },
  knight:     { label: 'Рыцарь',     plural: 'Рыцари',     c: '#5fa8f5' },
  pathfinder: { label: 'Путник',     plural: 'Путники',    c: '#4ade80' },
  recruit:    { label: 'Новобранец', plural: 'Новобранцы', c: '#97a1b2' },
};

const RANK_ORDER = ['creator', 'deity', 'legend', 'mythic', 'knight', 'pathfinder', 'recruit'];

// Высоты вершин (м). 2500+ — эпик (радужная метка, больше всего рейтинга),
// 2000–2500 — крепкая, ниже — обычная. null — высота пока неизвестна.
const PEAKS = {
  'Такао': 599,
  'Дзимба': 855,
  'Митакэ': 929,
  'Одакэ': 1266,
  'Сэнгэн': 802,
  'Таканосу': 834,
  'Танзава': 1491,
  'Кинпу-сан': 2599,
  'Кинтоки': 1212,
  'Кумотори': 2017,
  'Дзидзо-дакэ': 2764,
  'Каннон-дакэ': 2841,
  'Якуси-дакэ': 2780,
  'Камикочи': 1500,
  'Яцугатакэ': 2500,
  'Боноорэ': 969,
  'Мизугаки': 2230,
  'Акадакэ': 2899,
  'Цубакуро-дакэ': 2763,
  'Пунта дель Ранчи': null,
  'Пунта Кватро Сорелле': null,
};

const HEROES = [
  // ── Создатель ────────────────────────────────────────────
  { id: 'kianu', name: 'Киану', nick: null, status: 'active', rank: 'creator',
    roles: ['Организатор', 'Путеводитель', 'Навигатор', 'Разведчик'],
    place: 'Токио', quote: 'Осталось ещё 20 минут.', photo: null, hue: 355 },

  // ── Божества ─────────────────────────────────────────────
  { id: 'mark', name: 'Марк', nick: 'Акула-молоток', status: 'active', rank: 'deity',
    roles: ['Лекарь', 'Саппорт', 'Оруженосец', 'Водитель'],
    place: 'Токио', photo: null, hue: 205 },
  { id: 'nastya', name: 'Анастасия', nick: 'МВД', status: 'active', rank: 'deity',
    title: 'Токсичность',
    roles: ['Разведчик', 'Плюс вайб'],
    place: 'Токио', photo: null, hue: 320 },

  // ── Легенды ──────────────────────────────────────────────
  { id: 'sonya-birka', name: 'Соня', nick: 'Бирка', status: 'gone', rank: 'legend',
    title: 'Скалолаз',
    roles: ['Фото/видео', 'Мыльница', 'Скромняжка', 'Новое поколение'],
    place: 'Китай', photo: null, hue: 30 },
  { id: 'sonya-druid', name: 'Соня', nick: 'Друид', status: 'gone', rank: 'legend',
    roles: ['Плюс вайб'],
    place: 'Китай', photo: null, hue: 140 },
  { id: 'mira', name: 'Мира', nick: 'Торг', status: 'gone', rank: 'legend',
    roles: ['Плюс вайб', 'Разведчик', 'Алкоголик', 'Новое поколение'],
    place: 'Россия', photo: null, hue: 45 },
  { id: 'prohor', name: 'Прохор', nick: 'Колонка', status: 'active', rank: 'legend',
    roles: ['Плюс вайб', 'Разведчик', 'Новое поколение'],
    place: 'Токио', photo: null, hue: 15 },
  { id: 'maksim', name: 'Максим', nick: 'AI', status: 'gone', rank: 'legend',
    roles: ['Водитель', 'Интеллект', 'Скромняжка'],
    place: 'Россия', photo: null, hue: 55 },
  { id: 'miroslav', name: 'Мирослав', nick: '2010', status: 'gone', rank: 'legend',
    roles: ['Фото/видео', 'Плюс вайб', 'Новое поколение', 'Разведчик', 'Наркоман'],
    place: 'Россия', photo: null, hue: 35 },
  { id: 'marina', name: 'Марина', nick: 'Спортик', status: 'gone', rank: 'legend',
    roles: ['Фото/видео', 'Плюс вайб', 'Скромняжка'],
    place: 'Россия', photo: null, hue: 50 },
  { id: 'aleksandr', name: 'Александр', nick: 'Клёш', status: 'active', rank: 'legend',
    roles: ['Фото/видео', 'Плюс вайб'],
    place: 'Токио', photo: null, hue: 28 },
  { id: 'andrey', name: 'Андрей', nick: 'Стафовый кодер', status: 'gone', rank: 'legend',
    roles: ['Наркоман', 'Разведчик'],
    place: 'Лондон', photo: null, hue: 42 },
  { id: 'viktor', name: 'Виктор', nick: null, status: 'gone', rank: 'legend',
    roles: [],
    place: 'неизвестно', photo: null, hue: 48 },

  // ── Мифики ───────────────────────────────────────────────
  { id: 'zhenya', name: 'Женя', nick: 'Валькирия', status: 'gone', rank: 'mythic',
    roles: ['Новое поколение'],
    place: 'Россия', photo: null, hue: 280 },
  { id: 'yura', name: 'Юра', nick: 'Нет пути домой', status: 'active', rank: 'mythic',
    roles: ['Водитель', 'Скромняжка'],
    place: 'Токио', photo: null, hue: 250 },
  { id: 'tima-instruktor', name: 'Тима', nick: 'Инструктор', status: 'active', rank: 'mythic',
    roles: ['Водитель', 'Скромняжка'],
    place: 'Токио', photo: null, hue: 300 },
  { id: 'ksyusha', name: 'Ксюша', nick: 'Ящер', status: 'active', rank: 'mythic',
    roles: ['Скромняжка'],
    place: 'Токио', photo: null, hue: 95 },
  { id: 'albina', name: 'Альбина', nick: null, status: 'active', rank: 'mythic',
    title: 'Художник',
    roles: ['Товарищ', 'Плюс вайб', 'Фото/видео', 'Новое поколение'],
    place: 'Токио', photo: null, hue: 335 },
  { id: 'ulyana', name: 'Ульяна', nick: 'Медуза Горгона', status: 'active', rank: 'mythic',
    roles: ['Скромняжка'],
    place: 'Токио', photo: null, hue: 175 },
  { id: 'vika-raskladushka', name: 'Вика', nick: 'Раскладушка', status: 'active', rank: 'mythic',
    roles: ['Фото/видео'],
    place: 'Токио', photo: null, hue: 265 },
  { id: 'tima-sledopyt', name: 'Тима', nick: 'Следопыт', status: 'gone', rank: 'mythic',
    roles: ['Алкоголик', 'Наркоман', 'Новое поколение'],
    place: 'Латвия', photo: null, hue: 290 },
  { id: 'arkadiy', name: 'Аркадий', nick: 'Тибетский монах', status: 'gone', rank: 'mythic',
    roles: ['Разведчик'],
    place: 'Китай', photo: null, hue: 310 },

  // ── Рыцари ───────────────────────────────────────────────
  { id: 'anya-poteryashka', name: 'Аня', nick: 'Потеряшка', status: 'active', rank: 'knight',
    roles: [],
    place: 'Токио', photo: null, hue: 215 },
  { id: 'eson', name: 'Эсон', nick: 'Турбонаддув', status: 'active', rank: 'knight',
    roles: [],
    place: 'Токио', photo: null, hue: 200 },
  { id: 'tadahiro', name: 'Тадахиро', nick: 'Элайджо', status: 'active', rank: 'knight',
    roles: ['Фото/видео'],
    place: 'Токио', photo: null, hue: 190 },

  // ── Путники ──────────────────────────────────────────────
  { id: 'anya-glina', name: 'Аня', nick: 'Глиномес', status: 'gone', rank: 'pathfinder',
    roles: [],
    place: 'неизвестно', photo: null, hue: 25 },
  { id: 'vanya', name: 'Ваня', nick: 'Енот', status: 'active', rank: 'pathfinder',
    roles: [],
    place: 'Токио', photo: null, hue: 155 },
  { id: 'ira', name: 'Ира', nick: 'Мать Кабанов', status: 'gone', rank: 'pathfinder',
    roles: [],
    place: 'Китай', photo: null, hue: 130 },
  { id: 'kseniya', name: 'Ксения', nick: null, status: 'gone', rank: 'pathfinder',
    roles: [],
    place: 'неизвестно', photo: null, hue: 145 },

  // ── Новобранцы ───────────────────────────────────────────
  { id: 'anya-2', name: 'Аня', nick: null, status: 'active', rank: 'recruit',
    roles: ['Новое поколение'],
    place: 'Токио', photo: null, hue: 210 },
  { id: 'yulya', name: 'Юля', nick: null, status: 'active', rank: 'recruit',
    roles: ['Новое поколение'],
    place: 'Токио', photo: null, hue: 195 },
  { id: 'masha', name: 'Маша', nick: null, status: 'active', rank: 'recruit',
    roles: [],
    place: 'Токио', photo: null, hue: 230 },
  { id: 'matvey', name: 'Матвей', nick: 'Распутник', status: 'active', rank: 'recruit',
    roles: ['Наркоман', 'Новое поколение'],
    place: 'Токио', photo: null, hue: 10 },
  { id: 'irina', name: 'Ирина', nick: null, status: 'active', rank: 'recruit',
    roles: [],
    place: 'Токио', photo: null, hue: 220 },
  { id: 'natalya', name: 'Наталья', nick: null, status: 'gone', rank: 'recruit',
    roles: [],
    place: 'неизвестно', photo: null, hue: 205 },
  { id: 'vika', name: 'Вика', nick: null, status: 'active', rank: 'recruit',
    roles: [],
    place: 'Токио', photo: null, hue: 260 },
];

// ── Летопись хайков ──────────────────────────────────────
// Порядок — хронологический. crew — id героев из HEROES.

const HIKES = [
  { name: 'Дзимба → Такао', peaks: ['Дзимба', 'Такао'],
    crew: ['kianu', 'mark', 'ira'] },
  { name: 'Митакэ — Одакэ', peaks: ['Митакэ', 'Одакэ'],
    crew: ['kianu', 'viktor', 'sonya-birka', 'mark'] },
  { name: 'Хаконэ: Сэнгэн → Таканосу', peaks: ['Сэнгэн', 'Таканосу'],
    crew: ['kianu', 'mark', 'viktor', 'sonya-birka'] },
  { name: 'Танзава', peaks: ['Танзава'],
    crew: ['kianu', 'viktor', 'mark', 'sonya-birka'] },
  { name: 'Дзимба → Такао', peaks: ['Дзимба', 'Такао'],
    crew: ['sonya-druid', 'sonya-birka', 'ira', 'kianu'] },
  { name: 'Кинпу-сан', peaks: ['Кинпу-сан'],
    crew: ['kianu', 'mark', 'sonya-druid', 'andrey'] },
  { name: 'Кинтоки-яма', peaks: ['Кинтоки'],
    crew: ['kianu', 'kseniya', 'arkadiy', 'nastya', 'andrey', 'miroslav', 'mark'] },
  { name: 'Кумотори', peaks: ['Кумотори'],
    crew: ['kianu', 'mark', 'andrey'] },
  { name: 'Хоо-дзан «Феникс»', peaks: ['Дзидзо-дакэ', 'Каннон-дакэ', 'Якуси-дакэ'],
    crew: ['ira', 'mark', 'tadahiro', 'tima-instruktor', 'nastya', 'kianu'] },
  { name: 'Камикочи', peaks: ['Камикочи'],
    crew: ['andrey', 'mark'] },
  { name: 'Яцугатакэ', peaks: ['Яцугатакэ'],
    crew: ['kianu', 'mark', 'marina', 'anya-glina', 'natalya', 'nastya'] },
  { name: 'Боноорэ', peaks: ['Боноорэ'],
    crew: ['natalya', 'anya-glina', 'maksim', 'arkadiy', 'aleksandr', 'nastya', 'kianu'] },
  { name: 'Мизугаки', peaks: ['Мизугаки'],
    crew: ['mira', 'marina', 'nastya', 'kianu', 'prohor', 'tima-instruktor', 'tima-sledopyt', 'arkadiy', 'maksim', 'mark'] },
  { name: 'Акадакэ', peaks: ['Акадакэ'],
    crew: ['albina', 'tima-sledopyt', 'prohor', 'anya-poteryashka', 'mark', 'marina', 'nastya', 'ulyana', 'vika-raskladushka', 'kianu'] },
  { name: 'Цубакуро-дакэ', peaks: ['Цубакуро-дакэ'],
    crew: ['matvey', 'nastya', 'ira', 'albina', 'ulyana', 'marina', 'aleksandr', 'ksyusha', 'kianu'] },
  { name: 'Безымянная тропа', peaks: [],
    crew: ['aleksandr', 'prohor', 'masha', 'anya-poteryashka', 'ksyusha', 'ulyana', 'vika-raskladushka', 'yura', 'nastya', 'mark', 'albina', 'kianu'] },
  { name: 'Пунта дель Ранчи (Италия)', peaks: ['Пунта дель Ранчи'],
    crew: ['kianu'] },
  { name: 'Пунта Кватро Сорелле (Италия)', peaks: ['Пунта Кватро Сорелле'],
    crew: ['kianu'] },
];
